-- Migracja danych statusów zamówień: stare → nowe
-- Mapowanie:
--   KALKULACJA          → PLANOWANE
--   ZLOZONE             → DOGADYWANE
--   KOREKTY             → DOGADYWANE
--   ZATWIERDZONE        → PRODUKOWANE
--   KONTROLA_JAKOSCI    → WYPRODUKOWANE
--   PLYNIE              → WYSLANE
--   W_PORCIE            → WYSLANE
--   W_MAGAZYNIE         → ODEBRANE
--   ZAKONCZONE          → ODEBRANE

BEGIN;

-- 1. Konwertuj kolumny enum → text
ALTER TABLE "ImportOrder" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "ImportOrder" ALTER COLUMN "status" TYPE text USING "status"::text;
ALTER TABLE "OrderStatusHistory" ALTER COLUMN "fromStatus" TYPE text USING "fromStatus"::text;
ALTER TABLE "OrderStatusHistory" ALTER COLUMN "toStatus" TYPE text USING "toStatus"::text;
ALTER TABLE "OrderTask" ALTER COLUMN "status" TYPE text USING "status"::text;
ALTER TABLE "ImportOrderPayment" ALTER COLUMN "status" TYPE text USING "status"::text;
ALTER TABLE "OrderFile" ALTER COLUMN "status" TYPE text USING "status"::text;

-- 2. Zmapuj stare wartości na nowe
UPDATE "ImportOrder" SET "status" = CASE "status"
  WHEN 'KALKULACJA' THEN 'PLANOWANE'
  WHEN 'ZLOZONE' THEN 'DOGADYWANE'
  WHEN 'KOREKTY' THEN 'DOGADYWANE'
  WHEN 'ZATWIERDZONE' THEN 'PRODUKOWANE'
  WHEN 'KONTROLA_JAKOSCI' THEN 'WYPRODUKOWANE'
  WHEN 'PLYNIE' THEN 'WYSLANE'
  WHEN 'W_PORCIE' THEN 'WYSLANE'
  WHEN 'W_MAGAZYNIE' THEN 'ODEBRANE'
  WHEN 'ZAKONCZONE' THEN 'ODEBRANE'
  ELSE 'PLANOWANE'
END;

UPDATE "OrderStatusHistory" SET "fromStatus" = CASE "fromStatus"
  WHEN 'KALKULACJA' THEN 'PLANOWANE'
  WHEN 'ZLOZONE' THEN 'DOGADYWANE'
  WHEN 'KOREKTY' THEN 'DOGADYWANE'
  WHEN 'ZATWIERDZONE' THEN 'PRODUKOWANE'
  WHEN 'KONTROLA_JAKOSCI' THEN 'WYPRODUKOWANE'
  WHEN 'PLYNIE' THEN 'WYSLANE'
  WHEN 'W_PORCIE' THEN 'WYSLANE'
  WHEN 'W_MAGAZYNIE' THEN 'ODEBRANE'
  WHEN 'ZAKONCZONE' THEN 'ODEBRANE'
  ELSE "fromStatus"
END WHERE "fromStatus" IS NOT NULL;

UPDATE "OrderStatusHistory" SET "toStatus" = CASE "toStatus"
  WHEN 'KALKULACJA' THEN 'PLANOWANE'
  WHEN 'ZLOZONE' THEN 'DOGADYWANE'
  WHEN 'KOREKTY' THEN 'DOGADYWANE'
  WHEN 'ZATWIERDZONE' THEN 'PRODUKOWANE'
  WHEN 'KONTROLA_JAKOSCI' THEN 'WYPRODUKOWANE'
  WHEN 'PLYNIE' THEN 'WYSLANE'
  WHEN 'W_PORCIE' THEN 'WYSLANE'
  WHEN 'W_MAGAZYNIE' THEN 'ODEBRANE'
  WHEN 'ZAKONCZONE' THEN 'ODEBRANE'
  ELSE "toStatus"
END;

UPDATE "OrderTask" SET "status" = CASE "status"
  WHEN 'KALKULACJA' THEN 'PLANOWANE'
  WHEN 'ZLOZONE' THEN 'DOGADYWANE'
  WHEN 'KOREKTY' THEN 'DOGADYWANE'
  WHEN 'ZATWIERDZONE' THEN 'PRODUKOWANE'
  WHEN 'KONTROLA_JAKOSCI' THEN 'WYPRODUKOWANE'
  WHEN 'PLYNIE' THEN 'WYSLANE'
  WHEN 'W_PORCIE' THEN 'WYSLANE'
  WHEN 'W_MAGAZYNIE' THEN 'ODEBRANE'
  WHEN 'ZAKONCZONE' THEN 'ODEBRANE'
  ELSE "status"
END WHERE "status" IS NOT NULL;

UPDATE "ImportOrderPayment" SET "status" = CASE "status"
  WHEN 'KALKULACJA' THEN 'PLANOWANE'
  WHEN 'ZLOZONE' THEN 'DOGADYWANE'
  WHEN 'KOREKTY' THEN 'DOGADYWANE'
  WHEN 'ZATWIERDZONE' THEN 'PRODUKOWANE'
  WHEN 'KONTROLA_JAKOSCI' THEN 'WYPRODUKOWANE'
  WHEN 'PLYNIE' THEN 'WYSLANE'
  WHEN 'W_PORCIE' THEN 'WYSLANE'
  WHEN 'W_MAGAZYNIE' THEN 'ODEBRANE'
  WHEN 'ZAKONCZONE' THEN 'ODEBRANE'
  ELSE "status"
END WHERE "status" IS NOT NULL;

UPDATE "OrderFile" SET "status" = CASE "status"
  WHEN 'KALKULACJA' THEN 'PLANOWANE'
  WHEN 'ZLOZONE' THEN 'DOGADYWANE'
  WHEN 'KOREKTY' THEN 'DOGADYWANE'
  WHEN 'ZATWIERDZONE' THEN 'PRODUKOWANE'
  WHEN 'KONTROLA_JAKOSCI' THEN 'WYPRODUKOWANE'
  WHEN 'PLYNIE' THEN 'WYSLANE'
  WHEN 'W_PORCIE' THEN 'WYSLANE'
  WHEN 'W_MAGAZYNIE' THEN 'ODEBRANE'
  WHEN 'ZAKONCZONE' THEN 'ODEBRANE'
  ELSE "status"
END WHERE "status" IS NOT NULL;

-- 3. Drop stary enum, utwórz nowy
DROP TYPE "OrderStatus";
CREATE TYPE "OrderStatus" AS ENUM (
  'PLANOWANE',
  'DOGADYWANE',
  'PRODUKOWANE',
  'WYPRODUKOWANE',
  'WYSLANE',
  'ODEBRANE'
);

-- 4. Konwertuj text → nowy enum
ALTER TABLE "ImportOrder" ALTER COLUMN "status" TYPE "OrderStatus" USING "status"::"OrderStatus";
ALTER TABLE "ImportOrder" ALTER COLUMN "status" SET DEFAULT 'PLANOWANE'::"OrderStatus";
ALTER TABLE "OrderStatusHistory" ALTER COLUMN "fromStatus" TYPE "OrderStatus" USING "fromStatus"::"OrderStatus";
ALTER TABLE "OrderStatusHistory" ALTER COLUMN "toStatus" TYPE "OrderStatus" USING "toStatus"::"OrderStatus";
ALTER TABLE "OrderTask" ALTER COLUMN "status" TYPE "OrderStatus" USING "status"::"OrderStatus";
ALTER TABLE "ImportOrderPayment" ALTER COLUMN "status" TYPE "OrderStatus" USING "status"::"OrderStatus";
ALTER TABLE "OrderFile" ALTER COLUMN "status" TYPE "OrderStatus" USING "status"::"OrderStatus";

COMMIT;
